# Server Configuration
server.port=8081

# Spring Application Name
spring.application.name=AI-Interview-Agent

# MongoDB Database Configuration
# This connects to a local MongoDB instance and a database named 'ai_interview_auth'
spring.data.mongodb.uri=mongodb://localhost:27017/ai_interview

app.jwt.secret=YmFidWVAMTIzYmFidWVAMTIzYmFidWVAMTIzc2VjdXJla2V5
app.jwt.expiration-ms=86400000

gemini.api.key=AIzaSyCQbmqnX4Bg8lRXcxXuoptSj25SusjY2BY
